-- nvim-mason.lua Mason setup
-- Last Changed:2026-02-28 15:55:29
return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "arduino-language-server",
        "asm-lsp",
        "asmfmt",
        "autopep8",
        "awk-language-server",
        "bash-debug-adapter",
        "bash-language-server",
        "bibtex-tidy",
        "clang-format",
        "clangd",
        "cmake-language-server",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "cortex-debug",
        "cpplint",
        "cpptools",
        "debugpy",
        "flake8",
        "gitui",
        "json-lsp",
        "lua-language-server",
        "markdown-oxide",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "neocmakelsp",
        "prettier",
        "shellcheck",
        "shfmt",
        "stylua",
        "taplo",
        "texlab",
        "yaml-language-server",
      },
    },
  },
  {
    "mason-org/mason-lspconfig.nvim",
  },
}
